### ISSUE TITLE
Use IMauiInitializeService interface in conjunction with UsePageResolver startup extension.

### ISSUE THREAD

**Issue by bakerhillpins** [matt-goldman/Maui.Plugins.PageResolver#10]
This was to be a Feature Request but it appears there's no distinction between the 2 even though it's an option on the "New Issue" page.

I've been working through a bunch of different Navigation and startup things over the past few days and I believe that you could register a resolver initialization class as an `IMauiInitializeService` in the startup extension method and this would allow it to be placed anywhere in the builder chain as it will be called within the `MauiAppBuilder.Build` method. It could even be setup so that it supports multiple calls in case the code is referenced from multiple libraries. 

**Describe the solution you'd like**

Create a class that  `IMauiInitializeService`  that's registered which initializes the Resolver [during the `MauiAppBuilder.Build` method call](https://github.com/dotnet/maui/blob/8509b26238a86576fa1416a9582573166e335a18/src/Core/src/Hosting/MauiAppBuilder.cs#L157).

```

    public static void UsePageResolver(this IServiceCollection sc)
    {
        sc.AddSingleton<IMauiInitializeService, Resolver.Initializer>();
    }

    public static MauiAppBuilder UsePageResolver( this MauiAppBuilder builder )
    {
        builder.Services.AddSingleton<IMauiInitializeService, Resolver.Initializer>();

        return builder;
    }



    public static class Resolver
    {
        internal class Initializer : IMauiInitializeService
        {
#region Implementation of IMauiInitializeService

            /// <inheritdoc />
            public void Initialize( IServiceProvider services )
            {
                if ( Resolver.scope == null )
                {
                    Resolver.RegisterServiceProvider( services );
                }
            }

#endregion
        }
...
    }


```

**Comment by bakerhillpins** [comment]
I just threw together a quick test and it seems to work. I'll see about putting in a PR for review in the next day or so.

**Comment by matt-goldman** [comment]
Closed by: https://github.com/matt-goldman/Maui.Plugins.PageResolver/pull/11
