### ISSUE TITLE
Use TryAddEnumerable to only add IMauiInitializeService once.

### ISSUE THREAD

**Issue by bakerhillpins** [matt-goldman/Maui.Plugins.PageResolver#12]
After continuing to use MAUI and MS DI I've noted that changing the way the `IMauiInitializeService` is registered will reduce memory use...

Using `Services.TryAddEnumerable( ServiceDescriptor.Transient<IMauiInitializeService, Initializer>() );` will result in the `IMauiInitializeService` only being registered a single time. This is because the [extension method validates](https://stackoverflow.com/a/67655113) that the Service AND the Implementation have not been previously registered before it does so.

This will result in a smaller memory footprint and fewer registered services during runtime when the initialization occurs multiple times from say multiple assemblies that reference it.

**Comment by matt-goldman** [comment]
Closed by https://github.com/matt-goldman/Maui.Plugins.PageResolver/pull/11
