### ISSUE TITLE
Use Navigation.PushModalAsync<T> also for TabbedPage

### ISSUE THREAD

**Issue by ramonB1996** [matt-goldman/Maui.Plugins.PageResolver#15]
First of all; Thank you for this great library! It is really easy to use and saved me alot of time. I really think this should be a standard thing in .NET MAUI. 

**Is your feature request related to a problem? Please describe.**

At the moment, it is not possible to use `Navigation.PushModalAsync<T>` for a `TabbedPage`. It only works when `T` is of type `ContentPage`. 

**Describe the solution you'd like**

I would love to use this library for a `TabbedPage` in the same way I would use it with a `ContentPage`. So; `Navigation.PushModalAsync<TabbedPage>()`.

**Describe alternatives you've considered**

I did not consider anything yet, but I am curious as to why `T` is only allowed to be a `ContentPage`?

**Additional context**

**Comment by matt-goldman** [comment]
Hi Ramon, glad you like it! And thanks for taking the time to log this. 

To be honest the only reason I used ContentPage was because it was easier for me to test. It's easy enough to change it to Page, which would let it work with FlyoutPage and TabbedPage too. I just have to put the effort into testing it properly 😉

I'll let you know when I've got it fixed up. If I ping you when a pre-release version is available are you happy to test it in your app and give me feedback?

**Comment by ramonB1996** [comment]
> Hi Ramon, glad you like it! And thanks for taking the time to log this.
> 
> To be honest the only reason I used ContentPage was because it was easier for me to test. It's easy enough to change it to Page, which would let it work with FlyoutPage and TabbedPage too. I just have to put the effort into testing it properly 😉
> 
> I'll let you know when I've got it fixed up. If I ping you when a pre-release version is available are you happy to test it in your app and give me feedback?

Thank you very much for the fast response! I would happily test your solution when it is ready :) 
Thanks for taking your time to make the library even better!

Ramon

**Comment by matt-goldman** [comment]
Hi @ramonB1996, v1.0.7 is now live on NuGet. Please take it for a spin and let me know how it goes with TabbedPage.

**Comment by ramonB1996** [comment]
Thank you for your fast update! Will test this week and let you know my results.

**Comment by ramonB1996** [comment]
@matt-goldman It works perfectly for my Android project :) Thanks alot!
