### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by ramonB1996** [matt-goldman/Maui.Plugins.PageResolver#24]
**Describe the bug**
There is a small typo in the sample of your wiki-page in section 1.6 Option 3 (last line of code-sample).

**To Reproduce**
1. Go to 'https://github.com/matt-goldman/Maui.Plugins.PageResolver/wiki/1-Using-the-PageResolver'
2. Scroll down to Section 1.6, Option 3
3. See error in code sample

**Expected behavior**
```
builder.Services.AddPageResolver(pageMappings);
```
Should be:

```
builder.Services.UsePageResolver(pageMappings);
```

Sorry for not opening a PR, thought it would be 2 mins work for you probably :)

**Comment by matt-goldman** [comment]
Thanks! Nice catch :) Fixed.
