### ISSUE TITLE
Example of how to implement with FlyoutPage rather than Shell

### ISSUE THREAD

**Issue by memis1970** [matt-goldman/Maui.Plugins.PageResolver#25]
Hi, I'm trying to understand how to use this without using Shell for Navigation, specifically when using a FlyoutPage as MainPage

Would be great if you could advise how to achieve this, perhaps with a Demo project.

Coming from using Prism with XF where it was nice and simple, and being unable to use it with Maui, it's confusing how to achieve navigation, DI and MVVM combined for this use case....specifically how to set the MainPage as the FlyoutPage with the Detail as a ContentPage while injecting services and ViewModels into both the FlyoutPage and the Detail page.

Hope that makes sense and appreciate any help you can offer.

**Comment by matt-goldman** [comment]
The way to do this with Flyout navigation (or anything other than hierarchical navigation) is to use the XAML markup extensions. See: https://github.com/matt-goldman/Maui.Plugins.PageResolver/wiki/1-Using-the-PageResolver#14-use-in-your-code.

I don't have an example using FlyoutPage but I do have a demo in the sample app which should work the same way. See: https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/main/src/DemoProject/Pages/MarkupPage.xaml

Let me know if this helps 🙂

**Comment by memis1970** [comment]
Aah I see! 

BindingContext="{resolver:ResolveViewModel x:TypeArguments=vm:MarkupViewModel}"

Hadn't come across this way before. Looks good to me. Thanks for the reply.
