### ISSUE TITLE
Abstract classes shouldn't be added during resolution.

### ISSUE THREAD

**Issue by usmanmahmood** [matt-goldman/Maui.Plugins.PageResolver#27]
**Describe the bug**
If a class is an abstract class it should not be added while generating the code.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an abstract class
2. build the solution
3. Abstract class will be added in autogenerated code in UseAutodependencies function.

**Expected behaviour**
Abstract classes should not be added in UseAutodependencies function.

**Comment by matt-goldman** [comment]
Good catch, thanks! I should probably ignore abstract, I'm also going to add an ignore attribute.

**Comment by matt-goldman** [comment]
Sorry for the delay responding here. @IeuanWalker discovered that we can't exclude abstract classes as this causes interfaces to fail to be registered. If you have a suggestion about how to work around this I'd be happy to accept a PR. But if not, I have a new version releasing today that includes an `[Ignore]` attribute that you can use to exclude any classes from dependency registration.
