### ISSUE TITLE
Dynamic ViewModelLookup

### ISSUE THREAD

**Issue by IeuanWalker** [matt-goldman/Maui.Plugins.PageResolver#30]
**Is your feature request related to a problem? Please describe.**
Ability to add to `Dictionary<Type, Type> ViewModelLookup` in multiple places
https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L13C5-L13C77

**My Use case:** We have an app with 100s possibly even a thousand pages, so to manage all the registration and configs, each area/ routes of the app has there own app builder to manage their section, f.e. 
![image](https://github.com/matt-goldman/Maui.Plugins.PageResolver/assets/6544051/57ed667d-e7b6-41ef-821e-43056951df26)

Currently in order to add the manual mappings they all need to be initialised at the same time, but in order to keep the code as maintainable as possible i'd like to keep the mapping next to the registrations.

**Describe the solution you'd like**
I see 3 possible solutions using the current code -

- Make `InitialiseViewModelLookup` public and remove `ViewModelLookup.Clear();` (https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L31)
- Make `Dictionary<Type, Type> ViewModelLookup` public so we can manage it ourselves if we'd like (https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L13C5-L13C77)
- Create a new public method specific to adding to the dictionary

**Comment by IeuanWalker** [comment]
For now i've added 2 new public methods to `Resolver` - 
```csharp
public static void AddViewModelLookup<T1, T2>()
{
    ViewModelLookup.Add(typeof(T1), typeof(T2));
}
public static void AddViewModelLookup(Dictionary<Type, Type> ViewModelMappings)
{
    foreach (var mapping in ViewModelMappings)
    {
        ViewModelLookup.Add(mapping.Key, mapping.Value);
    }
}
```

So now I can keep the mappings next to each of the registrations and in different files -
```csharp
static class AppBuilderExtensions
{
	public static MauiAppBuilder RegisterWasteCalendar(this MauiAppBuilder builder)
	{
		builder.Services.AddTransient<AddressSearchPage>();
		builder.Services.AddTransient<AddressSearchViewModel>();

		builder.Services.AddTransient<DisplayPage>();
		builder.Services.AddTransient<DisplayViewModel>();
		Resolver.AddViewModelLookup<DisplayPage, DisplayViewModel>();

		builder.Services.AddTransient<RemindersPage>();
		builder.Services.AddTransient<RemindersViewModel>();
		Resolver.AddViewModelLookup<RemindersPage, RemindersViewModel>();

		builder.Services.AddTransient<AddPopup>();
		builder.Services.AddTransient<AddReminderViewModel>();
		Resolver.AddViewModelLookup<AddPopup, AddReminderViewModel>();

		return builder;
	}
}
```

**Comment by matt-goldman** [comment]
I wonder if an easier approach here is to go back to the simple extension methods I had in v1, i.e. extensions on `IServiceCollection` and `MauiAppBuilder`, rather than using `IMauiInitializeService`. See #11. Pretty sure this would also solve your problem right?

**Comment by matt-goldman** [comment]
In fact we really shouldn't be using `IMauiInitializeService` anyway. It's a temporary workaround that will likely get deprecated, and is not even the right use case.

**Comment by matt-goldman** [comment]
Sorry just getting back to this now. I misunderstood - yes your approach here is great. My comments above are unrelated (although still important). I think actually the `Resovler` class itself should be `internal` rather than `public`, but then I can add a method similar to yours to `StartupExtensions`.

I've got a PR incoming for this, I'll add you as a reviewer so I can get your feedback on whether this will work for you.
