### ISSUE TITLE
make it work on desktops

### ISSUE THREAD

**Issue by eduardoagr** [matt-goldman/Maui.Plugins.PageResolver#41]
**Is your feature request related to a problem? Please describe.**
I would like, to be able to do

`App.Current.OpenWindow<TurbineDetailPage>();`

**Comment by eduardoagr** [comment]
I have a question If I use your plugin, when you release, I don't have to do this. 

` var viewModel = _serviceProvider.GetRequiredService<TurbineDetailPageViewModel>();
 viewModel.SelectedTurbine = (TurbinePin)turbine;

 var page = _serviceProvider.GetRequiredService<TurbineDetailPage>();
 page.BindingContext = viewModel;`

**Comment by matt-goldman** [comment]
Yes you won't have to do that, you'll be able to constructor inject your ViewModel. I'll make sure there's a sample in the demo project.

**Comment by matt-goldman** [comment]
@eduardoagr version 2.5.2 has just been released which includes this feature. I've updated the demo project as well with some examples.

**Comment by eduardoagr** [comment]
could you provide me any code snippet to do this please

**Comment by matt-goldman** [comment]
@eduardoagr you can see some examples here: https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/main/src/DemoProject/ViewModels/DesktopPageViewModel.cs

It's pretty simple though, just:

```csharp
var myWindow = App.Current?.OpenWindow<MyPage>();
```

You can also pass parameters, either for the page or the page's binding context, same as with page navigation.
